name: HotBlock
main: surva\hotblock\HotBlock
version: 1.2.5
api: 5.0.0

softdepend: ["EconomyAPI", "BedrockEconomy", "Capital", "InfoAPI"]

author: survanetwork
description: A funny PvP minigame
website: https://dev.surva.net/plugins/#hotblock
